name: CWTools CI

on:
  push:
    branches:    
    - master
    paths:
    - '*/**/*.txt'
    - '*/**/*.yml'
    - '*/**/*.gfx'
    - '*/**/*.gui'
    - '!.*/**'
  pull_request:
    paths:
    - '*/**/*.txt'
    - '*/**/*.yml'
    - '*/**/*.gfx'
    - '*/**/*.gui'
    - '!.*/**'

jobs:
  cwtools_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: Yard1/CWTools-action@master
      with:
        suppressedOffenceCategories: '{"failure":[], "warning":["CW242"], "notice":[]}' # suppress empty field warnings
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
