name: CWTools CI

on:
  push:
    branches:    
    - master
    paths:
    - '**/*.txt'
    - '**/*.yml'
    - '**/*.gfx'
    - '**/*.gui'
    - '!.**'
    - '!tutorial/**'
    - '!changelog.txt'
    - '!interface/credits.txt'
  pull_request:
    branches:    
    - master
    paths:
    - '**/*.txt'
    - '**/*.yml'
    - '**/*.gfx'
    - '**/*.gui'
    - '!.**'
    - '!tutorial/**'
    - '!changelog.txt'
    - '!interface/credits.txt'

jobs:
  cwtools_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: cwtools/cwtools-action@v1.0.0
      with:
        game: hoi4
        locLanguages: "english russian"
        suppressedOffenceCategories: '{"failure":["CW226"], "warning":["CW242"], "notice":[]}' # suppress CW226 localisation commands and CW242 empty field warnings
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload output.json
      if: always()
      uses: actions/upload-artifact@v1.0.0
      with:
        name: cwtools_output
        path: output.json
