name: Generate GitHub Pages

on:
  push:
    branches:
    - master
    - gh-pages
    paths:
    - '.github/workflows/Generate GitHub Pages.yml'
    - '.github-pages/**/*'
    - '.gitignore'
    - 'images/**/*'
    - 'gfx/interface/goals/**/*.dds'
    - 'gfx/interface/ideas/**/*.dds'
    - 'gfx/interface/goals/**/*.tga'
    - 'gfx/interface/ideas/**/*.tga'
    - 'interface/**/*.gfx'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GHPAGES_PUSH_TOKEN }}
        ref: master
    - name: Checkout gh-pages branch
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GHPAGES_PUSH_TOKEN }}
        ref: gh-pages
        path: gh-pages
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r $GITHUB_WORKSPACE/gh-pages/.github-pages/requirements.txt
    - name: Generate webpage
      run: |
        BEFORE=$(cat $GITHUB_EVENT_PATH | python -c "import sys, json; print(json.load(sys.stdin)['before'])")
        MODIFIED_FILES=""
        MODIFIED_FILES=$(curl -s 'https://api.github.com/repos/$GITHUB_REPOSITORY/compare/$BEFORE...$GITHUB_SHA' | python3 -c "import sys, json; files = json.load(sys.stdin)['files']; print(' '.join([x['filename'] for x in files]))" 2>/dev/null)
        echo $MODIFIED_FILES
        rm -r $GITHUB_WORKSPACE/gh-pages/gfx/interface/
        mkdir -p $GITHUB_WORKSPACE/gh-pages/gfx/interface/
        mv $GITHUB_WORKSPACE/gfx/interface/goals $GITHUB_WORKSPACE/gh-pages/gfx/interface/
        mv $GITHUB_WORKSPACE/gfx/interface/ideas $GITHUB_WORKSPACE/gh-pages/gfx/interface/
        mv $GITHUB_WORKSPACE/interface/ $GITHUB_WORKSPACE/gh-pages
        cd $GITHUB_WORKSPACE/gh-pages
        python .github-pages/hoi4_icon_search_gen.py --goals "./interface/eaw_goals.gfx" --ideas "./interface/eaw_ideas.gfx" --title "Equestria at War Icon Search" --favicon "./eaw_icon.png" --modified-images $MODIFIED_FILES
    - name: Commit and push files
      run: |
        cd $GITHUB_WORKSPACE/gh-pages
        git config --global user.email "antoni.baum@protonmail.com"
        git config --global user.name "Yard1"
        git add -A
        git commit -m "Update webpage (automatic)"
        git push
        
