name: Generate GitHub Pages

on:
  push:
    branches:
    - master
    - gh-pages
    paths:
    - '.github/workflows/Generate GitHub Pages.yml'
    - '.github-pages/**/*'
    - '.gitignore'
    - 'images/**/*'
    - 'gfx/interface/goals/**/*.dds'
    - 'gfx/interface/ideas/**/*.dds'
    - 'gfx/interface/goals/**/*.tga'
    - 'gfx/interface/ideas/**/*.tga'
    - 'interface/**/*.gfx'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GHPAGES_PUSH_TOKEN }}
        ref: master
    - name: Checkout gh-pages branch
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GHPAGES_PUSH_TOKEN }}
        ref: gh-pages
        path: gh-pages
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r $GITHUB_WORKSPACE/gh-pages/.github-pages/requirements.txt
    - name: Generate webpage
      run: |
        rm -r $GITHUB_WORKSPACE/gh-pages/gfx/texticons/
        rm -r $GITHUB_WORKSPACE/gh-pages/gfx/event_pictures/
        rm -r $GITHUB_WORKSPACE/gh-pages/gfx/interface/
        mkdir -p $GITHUB_WORKSPACE/gh-pages/gfx/interface/
        mv $GITHUB_WORKSPACE/gfx/texticons $GITHUB_WORKSPACE/gh-pages/gfx
        mv $GITHUB_WORKSPACE/gfx/event_pictures $GITHUB_WORKSPACE/gh-pages/gfx
        mv $GITHUB_WORKSPACE/gfx/interface/goals $GITHUB_WORKSPACE/gh-pages/gfx/interface
        mv $GITHUB_WORKSPACE/gfx/interface/ideas $GITHUB_WORKSPACE/gh-pages/gfx/interface
        mv $GITHUB_WORKSPACE/gfx/interface/decisions $GITHUB_WORKSPACE/gh-pages/gfx/interface
        mv $GITHUB_WORKSPACE/interface/ $GITHUB_WORKSPACE/gh-pages
        cd $GITHUB_WORKSPACE/gh-pages
        python .github-pages/hoi4_icon_search_gen.py --goals "./interface/eaw_goals.gfx" "./interface/ee2_goals.gfx" "./interface/ee2_goals.gfx" "./interface/ncr_goals.gfx" --ideas "./interface/eaw_ideas.gfx" "./interface/ee2_ideas.gfx" --texticons "./interface/etat_texticons.gfx" "./interface/eaw_texticons.gfx" --events "./interface/eaw_eventpictures.gfx" --decisions "./interface/eaw_decisions.gfx" --title "Equestria at War Icon Search" --favicon "./eaw_icon.png"
    - name: Commit and push files
      run: |
        cd $GITHUB_WORKSPACE/gh-pages
        if [ -z "$(git status --porcelain)" ]; then 
          exit 0
        fi
        git config --global user.email "antoni.baum@protonmail.com"
        git config --global user.name "Yard1"
        git add -A
        git commit -m "Update webpage (automatic)"
        git push
