name: Generate GitHub Pages

on:
  push:
    branches:
    - master
    - gh-pages
    paths:
    - '.github/workflows/Generate GitHub Pages.yml'
    - '.github-pages/**/*'
    - '.gitignore'
    - 'images/**/*'
    - 'gfx/interface/goals/**/*.dds'
    - 'gfx/interface/ideas/**/*.dds'
    - 'gfx/interface/goals/**/*.tga'
    - 'gfx/interface/ideas/**/*.tga'
    - 'interface/**/*.gfx'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout gh-pages branch
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: gh-pages
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r $GITHUB_WORKSPACE/gh-pages/.github-pages/requirements.txt
    - name: Generate webpage
      run: |
        mkdir -p $GITHUB_WORKSPACE/gh-pages/gfx/interface/
        mv $GITHUB_WORKSPACE/gfx/interface/goals $GITHUB_WORKSPACE/gh-pages/gfx/interface/
        mv $GITHUB_WORKSPACE/gfx/interface/ideas $GITHUB_WORKSPACE/gh-pages/gfx/interface/
        mv $GITHUB_WORKSPACE/interface/ $GITHUB_WORKSPACE/gh-pages
        cd $GITHUB_WORKSPACE/gh-pages
        python .github-pages/hoi4_icon_search_gen.py --goals "./interface/eaw_goals.gfx" --ideas "./interface/eaw_ideas.gfx" --title "Equestria at War Icon Search" --favicon "./eaw_icon.png"
        ls
    - name: Commit files
      run: |
        cd $GITHUB_WORKSPACE/gh-pages
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Update webpage" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'gh-pages'
        directory: '/home/runner/work/equestria_dev/equestria_dev/gh-pages'
