name: Generate GitHub Pages

on:
  push:
    branches: [ master ]
    paths:
    - 'gfx/interface/goals/**'
    - 'gfx/interface/ideas/**'
    - 'interface/**/*.gfx'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout github-pages branch
      uses: actions/checkout@v2
      with:
        branch: github-pages
        path: github-pages
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r $GITHUB_WORKSPACE/github-pages/.github-pages/requirements.txt
    - name: Generate webpage
      run: |
        mv $GITHUB_WORKSPACE/equestria-dev/gfx/interface/goals $GITHUB_WORKSPACE/github-pages
        mv $GITHUB_WORKSPACE/equestria-dev/gfx/interface/ideas $GITHUB_WORKSPACE/github-pages
        mv $GITHUB_WORKSPACE/equestria-dev/interface/ $GITHUB_WORKSPACE/github-pages
        cd $GITHUB_WORKSPACE/github-pages
        python .github-pages/hoi4_icon_search_gen.py --goals "./interface/eaw_goals.gfx" --ideas "./interface/eaw_ideas.gfx" --title "Equestria at War Icon Search" --favicon "./eaw_icon.png"
        find gfx/interface/ideas -type f  ! -name "*.png"  -delete
        find gfx/interface/goals -type f  ! -name "*.png"  -delete
        rm -r interface
    - name: Commit files
      run: |
        cd $GITHUB_WORKSPACE/github-pages
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Update webpage" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'github-pages'
